name: Release gingersnap

on:
  workflow_dispatch:
    inputs:
      cache-manager-ref:
        type: string
        default: main
      cache-manager-repository:
        type: string
        default: gingersnap-project/cache-manager
      db-syncer-ref:
        type: string
        default: main
      db-syncer-repository:
        type: string
        default: pminz/db-syncer
      operator-ref:
        type: string
        default: main
      operator-repository:
        type: string
        default: gingersnap-project/operator

jobs:

  trigger-workflow:
    uses: gingersnap/release/.github/workflows/trigger-build.yaml@main
    with: 
      cache-manager-ref: ${{ inputs.cache-manager-ref }}
      cache-manager-repository: ${{ inputs.cache-manager-repository }}
      db-syncer-ref: ${{ inputs.db-syncer-ref}}
      db-syncer-repository: {{ inputs.db-syncer-repository }}
      operator-ref: ${{ inputs.operator-ref}}
      operator-repository: {{ inputs.operator-repository }}