name: Trigger workflow for release

on:
  workflow_call:
    inputs:
      cache-manager-ref:
        type: string
        default: main
      db-syncer-ref:
        type: string
        default: main
      operator-ref:
        type: string
        default: main

jobs:

  cache-manager-images:
    uses: gingersnap-project/cache-manager/.github/workflows/create-tag.yml@main
    with:
      ref: ${{ inputs.cache-manager-ref }}

  db-syncer-image:
    uses: gingersnap-project/db-syncer/.github/workflows/create-tag.yml@main
    with:
      ref: ${{ inputs.db-syncer-ref }}
  
  operator: 
    if: success()
    needs: [cache-manager-images, db-syncer-image]
    uses: gingersnap-project/operator/.github/workflows/release.yaml@main
    with:
      ref: ${{ inputs.operator-ref }}


